import './globals.css'
import { Inter } from 'next/font/google'

import '@my-lib-org/mylib-core-styles/css/mylib-icons--js-import.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="App-header">
          <h1 className="App-title">
            React - `create-next-app (javascript)`
          </h1>
        </header>
        {children}
      </body>
    </html>
  )
}
