import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@my-lib-org/mylib-core-styles/css/mylib-icons--js-import.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="App-header">
          <h1 className="App-title">
            React - `create-next-app (typescript)`
          </h1>
        </header>
        {children}
      </body>
    </html>
  )
}
